In [110]:
import pandas as pd

In [139]:
df=pd.read_csv("IPL_2023_DATASET.csv")

In [140]:
df.head(500)

,Unnamed: 0,Player,Base Price,TYPE,COST IN ₹ (CR.),Cost IN $ (000),2022 Squad,Team,Base Price IN ₹,Base Price IN $
0,0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,NaN,NaN
1,1,Joshua Little,5000000,BOWLER,4.4,528.0,NaN,Gujarat Titans,NaN,NaN
2,2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,NaN,NaN
3,3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,NaN,NaN
4,4,Mohit Sharma,5000000,BOWLER,0.5,60.0,NaN,Gujarat Titans,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
495,495,Rajesh Mohanty,NaN,BOWLER,NaN,NaN,NaN,Unsold,2000000.0,24000.0
496,496,Ravi Sharma,NaN,BOWLER,NaN,NaN,NaN,Unsold,2000000.0,24000.0
497,497,Vikash Singh,NaN,BOWLER,NaN,NaN,NaN,Unsold,2000000.0,24000.0
498,498,Ruben Trumpelmann,NaN,BOWLER,NaN,NaN,NaN,Unsold,2000000.0,24000.0
499,499,Koushik Vasuki,NaN,BOWLER,NaN,NaN,NaN,Unsold,2000000.0,24000.0

In [141]:
df.shape

(568, 10)

In [142]:
df.columns

Index(['Unnamed: 0', 'Player', 'Base Price', 'TYPE', 'COST IN ₹ (CR.)',
       'Cost IN $ (000)', '2022 Squad', 'Team', 'Base Price IN ₹',
       'Base Price IN $'],
      dtype='object')

In [143]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [144]:
print(df.columns)

Index(['Player', 'Base Price', 'TYPE', 'COST IN ₹ (CR.)', 'Cost IN $ (000)',
       '2022 Squad', 'Team', 'Base Price IN ₹', 'Base Price IN $'],
      dtype='object')

In [145]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

for col in df.select_dtypes(include="object"):
    df[col] = df[col].str.strip()

In [146]:
df.isnull().sum()

player               0
base_price         325
type                 0
cost_in_₹_(cr.)    325
cost_in_$_(000)    325
2022_squad         338
team                 0
base_price_in_₹    243
base_price_in_$    243
dtype: int64

In [147]:
df["base_price"].fillna("Unknown", inplace=True)

# Step 1: NaN को Unsold
df["cost_in_₹_(cr.)"].fillna("Unsold", inplace=True)

# Step 2: 0.0 को भी Unsold
df["cost_in_₹_(cr.)"] = df["cost_in_₹_(cr.)"].replace(0.0, "Unsold")

# Similarly for cost_in_$_(000)
df["cost_in_$_(000)"].fillna("Unsold", inplace=True)
df["cost_in_$_(000)"] = df["cost_in_$_(000)"].replace(0.0, "Unsold")

# 2022_squad null ko replace
df["2022_squad"].fillna("Not in Squad", inplace=True)

# df["Base Price IN ₹"].fillna(0, inplace=True)
# df["Base Price IN $"].fillna(0, inplace=True)

In [148]:
df.head(500)

,player,base_price,type,cost_in_₹_(cr.),cost_in_$_(000),2022_squad,team,base_price_in_₹,base_price_in_$
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,NaN,NaN
1,Joshua Little,5000000,BOWLER,4.4,528.0,Not in Squad,Gujarat Titans,NaN,NaN
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,NaN,NaN
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,NaN,NaN
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,Not in Squad,Gujarat Titans,NaN,NaN
...,...,...,...,...,...,...,...,...,...
495,Rajesh Mohanty,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0
496,Ravi Sharma,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0
497,Vikash Singh,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0
498,Ruben Trumpelmann,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0
499,Koushik Vasuki,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0

“Auction ke data se deep insights nikaalna — kaun bikka, kaun nahi; kaun mehenga, kaun sasta; team kis type ke players pe paisa uda rahi hai.

In [149]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [150]:
# Base price in ₹
df["base_price_in_₹"] = df["base_price_in_₹"].fillna(0)
df["base_price_status"] = df["base_price_in_₹"].apply(lambda x: "Not Declared" if x == 0 else "Declared")

# Base price in $
df["base_price_in_$"] = df["base_price_in_$"].fillna(0)
df["base_price_status_$"] = df["base_price_in_$"].apply(lambda x: "Not Declared" if x == 0 else "Declared")

In [151]:
df.head(500)

,player,base_price,type,cost_in_₹_(cr.),cost_in_$_(000),2022_squad,team,base_price_in_₹,base_price_in_$,base_price_status,base_price_status_$
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
1,Joshua Little,5000000,BOWLER,4.4,528.0,Not in Squad,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,Not in Squad,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
...,...,...,...,...,...,...,...,...,...,...,...
495,Rajesh Mohanty,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
496,Ravi Sharma,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
497,Vikash Singh,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
498,Ruben Trumpelmann,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
499,Koushik Vasuki,Unknown,BOWLER,Unsold,Unsold,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared

In [152]:
df.dtypes

player                  object
base_price              object
type                    object
cost_in_₹_(cr.)         object
cost_in_$_(000)         object
2022_squad              object
team                    object
base_price_in_₹        float64
base_price_in_$        float64
base_price_status       object
base_price_status_$     object
dtype: object

In [167]:
df["cost_in_₹_(cr.)"] = (
    df["cost_in_₹_(cr.)"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("Cr.", "", regex=False)
    .str.replace("Cr", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

# Step 2: "Unsold", "-", "" जैसी values को NaN बना दो
df["cost_in_₹_(cr.)"] = df["cost_in_₹_(cr.)"].replace(["Unsold", "-", ""], pd.NA)

# Step 3: अब float में convert करो
df["cost_in_₹_(cr.)"] = pd.to_numeric(df["cost_in_₹_(cr.)"], errors="coerce")

df["cost_in_$_(000)"] = df["cost_in_$_(000)"].replace(["Unsold", "-", ""], pd.NA)

df["cost_in_$_(000)"] = pd.to_numeric(df["cost_in_$_(000)"], errors="coerce")
# # Step 4 (optional): Null values को drop कर दो (ताकि plot साफ बने)
# # df = df.dropna(subset=["cost_in_₹_(cr.)"])

# # df["base_price_in_₹"] = df["base_price_in_₹"].astype(float)
# # df["base_price_in_$"] = df["base_price_in_$"].astype(float)
# # df["cost_in_₹_(cr.)"] = df["cost_in_₹_(cr.)"].astype(float)
# # df["cost_in_$_(000)"] = df["cost_in_$_(000)"].astype(float)

# # df.dtypes

In [168]:
df["base_price_in_₹"] = df["base_price_in_₹"].astype(float)
# df["base_price_in_$"] = df["base_price_in_$"].astype(float)
df["cost_in_₹_(cr.)"] = df["cost_in_₹_(cr.)"].astype(float)
df["cost_in_$_(000)"] = df["cost_in_$_(000)"].astype(float)

df.dtypes

player                  object
base_price              object
type                    object
cost_in_₹_(cr.)        float64
cost_in_$_(000)        float64
2022_squad              object
team                    object
base_price_in_₹        float64
base_price_in_$        float64
base_price_status       object
base_price_status_$     object
dtype: object

In [169]:
df.head(500)

,player,base_price,type,cost_in_₹_(cr.),cost_in_$_(000),2022_squad,team,base_price_in_₹,base_price_in_$,base_price_status,base_price_status_$
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
1,Joshua Little,5000000,BOWLER,4.4,528.0,Not in Squad,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,Not in Squad,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
...,...,...,...,...,...,...,...,...,...,...,...
495,Rajesh Mohanty,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
496,Ravi Sharma,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
497,Vikash Singh,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
498,Ruben Trumpelmann,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
499,Koushik Vasuki,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared

In [170]:
df.head()

,player,base_price,type,cost_in_₹_(cr.),cost_in_$_(000),2022_squad,team,base_price_in_₹,base_price_in_$,base_price_status,base_price_status_$
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
1,Joshua Little,5000000,BOWLER,4.4,528.0,Not in Squad,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,Not in Squad,Gujarat Titans,0.0,0.0,Not Declared,Not Declared

In [172]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [174]:
df.head(500)

,player,base_price,type,cost_in_₹_(cr.),cost_in_$_(000),2022_squad,team,base_price_in_₹,base_price_in_$,base_price_status,base_price_status_$
0,Shivam Mavi,4000000,BOWLER,6.0,720.0,KKR,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
1,Joshua Little,5000000,BOWLER,4.4,528.0,Not in Squad,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
2,Kane Williamson,20000000,BATSMAN,2.0,240.0,SRH,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
3,K.S. Bharat,2000000,WICKETKEEPER,1.2,144.0,DC,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
4,Mohit Sharma,5000000,BOWLER,0.5,60.0,Not in Squad,Gujarat Titans,0.0,0.0,Not Declared,Not Declared
...,...,...,...,...,...,...,...,...,...,...,...
495,Rajesh Mohanty,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
496,Ravi Sharma,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
497,Vikash Singh,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
498,Ruben Trumpelmann,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared
499,Koushik Vasuki,Unknown,BOWLER,NaN,NaN,Not in Squad,Unsold,2000000.0,24000.0,Declared,Declared

In [177]:
df.to_csv("IPL_2023_CLEANED.csv", index=False)